services:
  app:
    image: laravelphp/php-fpm
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - apc-2024-2025-t1-01_queensway_rebo_laravel
    ports:
      - "8000:8000"
    environment:
      - PHP_FPM_INSTALL_XDEBUG=true
    depends_on:
      - mysql
    command: bash -c "sleep 10 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"  # Added a sleep to wait for MySQL

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/import_db.sh:/docker-entrypoint-initdb.d/import_db.sh
      - ./scripts/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql  # Mount the database dump
    networks:
      - apc-2024-2025-t1-01_queensway_rebo_laravel
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=rootpassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:

networks:
  apc-2024-2025-t1-01_queensway_rebo_laravel:
    driver: bridge
