version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: bash -c "sleep 15 && composer install && php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/import_db.sh:/docker-entrypoint-initdb.d/import_db.sh
      - ./scripts/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
      - ./storage:/var/www/storage

    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=rootpassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge

