version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "8000:8000"  # Port mapping: host:container
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
